### ISSUE TITLE
Attach several relation in one SQL-command

### ISSUE THREAD

**Issue by Denchick** [pg-sharding/spqr#521]
In the current version, you need to execute several SQL commands to attach multiple relations to the distribution. The commands are as follows:

```
ALTER DISTRIBUTION ds1 ATTACH RELATION a DISTRIBUTION KEY a_id;
ALTER DISTRIBUTION ds1 ATTACH RELATION b DISTRIBUTION KEY b_id HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds2 ATTACH RELATION c DISTRIBUTION KEY c_id_1 HASH FUNCTION IDENT,
                                                          c_id_2 HASH FUNCTION CITY;
```

It would be cool to set up this mapping in just one command. Something like this:

```
ALTER DISTRIBUTION ds1  ATTACH [
    (a a_id)
    (b b_id hash murmur)
    (c_id_1 hash ident c_id_2 hash city)
];
```

It seems strange, I agree. I'm sure it should be done in a more SQL-friendly way, maybe someone else has a better idea on how it could look.

**Comment by EinKrebs** [comment]
Fixed in #508
